const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Plugins.Tilemap,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.JavaScriptInEvents.Boardevents_Event41_Act2,
		C3.JavaScriptInEvents.Boardevents_Event42_Act2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.Boardevents_Event43_Act1,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.Endingevents_Event1_Act1
	];
};
self.C3_JsPropNameTable = [
	{CurrentTileID: 0},
	{MoveTo: 0},
	{Player: 0},
	{Board: 0},
	{TileNumber: 0},
	{Type: 0},
	{Tile: 0},
	{Player2: 0},
	{Player3: 0},
	{Player4: 0},
	{Dice: 0},
	{Mouse: 0},
	{Start: 0},
	{DiceTxt: 0},
	{BG: 0},
	{QuestionID: 0},
	{Question: 0},
	{Answer1: 0},
	{Answer2: 0},
	{Answer1ID: 0},
	{Correct: 0},
	{Answer1Txt: 0},
	{Answer2ID: 0},
	{Answer2Txt: 0},
	{ScoreBG: 0},
	{TurnBG: 0},
	{Player5: 0},
	{Player6: 0},
	{Player7: 0},
	{Player8: 0},
	{Score1: 0},
	{Score2: 0},
	{Score3: 0},
	{Score4: 0},
	{TurnsNum: 0},
	{TurnsTxt: 0},
	{YouWin: 0},
	{PlayerDisplay: 0},
	{WinnerScore: 0},
	{Keyboard: 0},
	{WinnerScoreNUM: 0},
	{Turn: 0},
	{MovesLeft: 0},
	{P1Score: 0},
	{P2Score: 0},
	{P3Score: 0},
	{P4Score: 0},
	{TotalTurn: 0},
	{QA_IDs: 0},
	{TempCorrect: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Board: class extends self.ITilemapInstance {},
	Tile: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Player3: class extends self.ISpriteInstance {},
	Player4: class extends self.ISpriteInstance {},
	Dice: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Start: class extends self.ISpriteInstance {},
	DiceTxt: class extends self.ITextInstance {},
	BG: class extends self.ISpriteInstance {},
	Question: class extends self.ITextInstance {},
	Answer1: class extends self.ISpriteInstance {},
	Answer2: class extends self.ISpriteInstance {},
	Answer1Txt: class extends self.ITextInstance {},
	Answer2Txt: class extends self.ITextInstance {},
	ScoreBG: class extends self.ISpriteInstance {},
	TurnBG: class extends self.ISpriteInstance {},
	Player5: class extends self.ISpriteInstance {},
	Player6: class extends self.ISpriteInstance {},
	Player7: class extends self.ISpriteInstance {},
	Player8: class extends self.ISpriteInstance {},
	Score1: class extends self.ITextInstance {},
	Score2: class extends self.ITextInstance {},
	Score3: class extends self.ITextInstance {},
	Score4: class extends self.ITextInstance {},
	TurnsNum: class extends self.ITextInstance {},
	TurnsTxt: class extends self.ITextInstance {},
	YouWin: class extends self.ITextInstance {},
	PlayerDisplay: class extends self.ISpriteInstance {},
	WinnerScore: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {}
}